version: '2'
services:
    canary-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/canary/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=canary
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
